version: "3.9"

services:
  # =========================================
  # ðŸ§© MODO DESARROLLO (live reload con ng serve)
  # =========================================
  frontend-dev:
    image: node:20-alpine
    container_name: frontend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start-docker"
    environment:
      - NODE_ENV=development

  # =========================================
  # ðŸš€ MODO PRODUCCIÃ“N (servido con Apache)
  # =========================================
  frontend:
    build: .
    container_name: frontend
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
